### ISSUE TITLE
Держать кучу optionов в скрипте - безобразие.

### ISSUE THREAD

**Issue by KOLANICH** [ololoepepe/MakabaCode#10]
Создавай динамически, список вынеси в ресурс  (отдельный файл), ресурс тяни с помощью GM_getResourceText и дополнительной строки в блоке метаданных

**Comment by ololoepepe** [comment]
Вот ты и сделай. Это ж так, заплатка над макабой, лишь бы работала, а на чистоту и качество кода строго похуй. Лень мне этим заниматься.
