### ISSUE TITLE
Link "Показать текст полностью" does not work if the userscript is enabled. 

### ISSUE THREAD

**Issue by nukede** [ololoepepe/MakabaCode#2]
If you enable the usersciprt and go to /pr, the link "Показать текст полностью"  will not work. But when you stop the usersciprt the link will work correctly. This issue appears only when the [code][/code] tags are separated by Abu-shit-code (c); if only the plain text hides under the link everything works correctly. 
![screenshot_47](https://cloud.githubusercontent.com/assets/2340741/7124369/f2fe2efa-e230-11e4-8862-7b09eda17d11.png)

**Comment by ololoepepe** [comment]
Fixed.
