### ISSUE TITLE
Добавь наконец автообновление

### ISSUE THREAD

**Issue by SergeyVSB** [ololoepepe/MakabaCode#7]
Надоело вручную проверять

**Comment by ololoepepe** [comment]
А я его поддерживать не планирую. Работает и ладно. Если только кто-то пулл-реквест сделает, тогда да. Если нужно автообновление - пили, замерджу.

**Comment by SergeyVSB** [comment]
Змерджь https://github.com/ololoepepe/MakabaCode/commit/45f8a08c8865876afe5d0f6ba4bae0468ce5f024 при следующих фиксах

**Comment by ololoepepe** [comment]
Ветка develop заброшена, только лишний гемор с ней. Изменения добавлю в master.
