### ISSUE TITLE
greasyfork для кого?

### ISSUE THREAD

**Issue by KOLANICH** [ololoepepe/MakabaCode#8]

**Comment by ololoepepe** [comment]
Для веб-макак? Веб-разработка не является моим основным направлением деятельности, поэтому я не в курсе всех ваших приблуд.

**Comment by ololoepepe** [comment]
Все правильно? https://greasyfork.org/ru/scripts/11768-makabacode

**Comment by KOLANICH** [comment]
Вроде да. Не забудь настроить вебхук для гитхаба (чтобы с гитхаба автоматически тянуло туда, когда пушишь).

**Comment by ololoepepe** [comment]
Сделал.
