### ISSUE TITLE
textContent используй вместо ручного декодирования сущностей.

### ISSUE THREAD

**Issue by KOLANICH** [ololoepepe/MakabaCode#9]

**Comment by ololoepepe** [comment]
Номера строк укажи, пазязя. Хотя бы несколько. Я уже не помню что там и где происходит, несколько месяцев не открывал.

**Comment by KOLANICH** [comment]
260-262

**Comment by ololoepepe** [comment]
Ага, понял тебя. Может когда-то переделаю, но не сейчас, потому что там это дело уходит далеко в другие функции, как бы не сломалось чего (отлаживать нет желания сейчас). Будет настроение - сделаю.
